# Generated by Django 3.2.8 on 2022-06-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, verbose_name='userID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('numberOfSudokus', models.IntegerField(default=0, verbose_name='numberOfSudokus')),
            ],
        ),
        migrations.CreateModel(
            name='sudoku',
            fields=[
                ('sudokuID', models.AutoField(primary_key=True, serialize=False, verbose_name='sudokuID')),
                ('row1', models.IntegerField(default=0, verbose_name='row1')),
                ('row2', models.IntegerField(default=0, verbose_name='row2')),
                ('row3', models.IntegerField(default=0, verbose_name='row3')),
                ('row4', models.IntegerField(default=0, verbose_name='row4')),
                ('row5', models.IntegerField(default=0, verbose_name='row5')),
                ('row6', models.IntegerField(default=0, verbose_name='row6')),
                ('row7', models.IntegerField(default=0, verbose_name='row7')),
                ('row8', models.IntegerField(default=0, verbose_name='row8')),
                ('row9', models.IntegerField(default=0, verbose_name='row9')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudokuScanner.user')),
            ],
        ),
    ]
