# Generated by Django 3.2.8 on 2022-06-14 04:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('numberOfSudokus', models.IntegerField(default=0, verbose_name='numberOfSudokus')),
            ],
        ),
        migrations.CreateModel(
            name='sudoku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('digits', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=81)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudokuScanner.user')),
            ],
        ),
    ]
