# Generated by Django 3.2.8 on 2022-06-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuScanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False, verbose_name='imageID')),
                ('imageValue', models.ImageField(upload_to='sudoku_images', verbose_name='imageValue')),
            ],
        ),
    ]
