# Generated by Django 3.2.8 on 2022-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuScanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='digits',
            field=models.IntegerField(),
        ),
    ]
