# Generated by Django 3.2.8 on 2022-06-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuScanner', '0003_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numberOfSudokus',
        ),
    ]
