# Generated by Django 3.2.8 on 2022-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuScanner', '0004_auto_20220619_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
