# Generated by Django 3.2.8 on 2022-06-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudokuScanner', '0005_remove_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageValue',
            field=models.ImageField(upload_to='sudoku_images${imageID}', verbose_name='imageValue'),
        ),
    ]
